import { Geist, Geist_Mono } from "next/font/google";
import "@/public/css/globals.css";
import Navbar from "@/components/Navbar/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-500">
        <div className="flex flex-col h-dvh">
          <div className="h-2/12"><Navbar /></div>
          <div className="bg-slate-300 h-10/12"> {children}</div>
        </div>
      </body>
    </html>
  );
}
